# Use a imagem base do Node.js com Alpine
FROM node:20-alpine

# Instale dependências necessárias para construir módulos nativos
RUN apk add --no-cache python3 make g++

# Crie e defina o diretório de trabalho
WORKDIR /app

# Copie o package.json e o package-lock.json para o contêiner
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código da aplicação
COPY . .

# Exponha a porta que a aplicação irá usar
EXPOSE 3001

# Comando para iniciar a aplicação
CMD ["npm", "start"]
