name: Deploy to AWS EC2 (staging)

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login no DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e push da imagem Docker do backend (staging)
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:staging .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:staging

      - name: Build e push da imagem Docker do frontend (staging)
        run: |
          cd frontend
          cp .env.staging .env  # Copia o arquivo .env.staging para .env
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:staging .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:staging

      - name: Adicionar chave SSH
        run: |
          echo "${{ secrets.EC2_SSH_STAGING }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

      - name: SSH e deploy no EC2 (Backend)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER_STAGING }}
          key_path: /tmp/id_rsa
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend:staging
            docker stop backend-staging || true
            docker rm backend-staging || true
            docker run -d --name backend-staging -p 3001:3001 ${{ secrets.DOCKER_USERNAME }}/backend:staging

      - name: SSH e deploy no EC2 (Frontend)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER_STAGING }}
          key_path: /tmp/id_rsa
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:staging
            docker stop frontend-staging || true
            docker rm frontend-staging || true
            docker run -d --name frontend-staging -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/frontend:staging
